CREATE TABLE CLIENTES (
    ID_CLIENTES             NUMBER(10) PRIMARY KEY,
    APELLIDO_NOMBRE         VARCHAR2(150) NOT NULL,
    SUCURSAL                VARCHAR2(50),
    SCORING_INTERNO         NUMBER(10), 
    MONTO_SOLICITADO        NUMBER(15,2),
    PROVINCIA               VARCHAR2(50)
    )


CREATE TABLE HISTORIAL_PAGOS (
    ID_CLIENTES     NUMBER(10) PRIMARY KEY,
    ATRASO_MINIMO   INT,
    ESTADO          VARCHAR(20),
    LIMITE_ACTUAL   INT
)